### PR TITLE
Add logging for GetProjectionRaw() and related logic.

### PR DESCRIPTION
**Pull request by codyherzog**
This is an experimental fix for testing and review. It's trying to address the issue of subtle warping that occurs when tilting about the forward looking axis.

I don't know if this has any bad side effects. It seems better overall in my configuration, but I don't understand the math, so I'm uncomfortable recommending this for merge unless someone else reviews and it gets tested on different headsets. I'm on Quest 3 using Virtual Desktop.

### CODE REVIEW

**Comment by codyherzog** [comment]
Attaching modified d3d9.dll for anyone who wants to test but is unable to build from source. Backup the old DLL, then unzip the new DLL and copy it into your Halo root folder. Switch back and forth between the DLL versions and play around with tilting your head side to side so that your ear touches your left and right shoulder. Pay attention to whether or not you see any perspective distortion or weird stretching/flexing of geometry/textures. This DLL is the same as the 1.1.0 release, but with the experimental head tilt warping fix.

[d3d9.zip](https://github.com/user-attachments/files/17997386/d3d9.zip)

**Comment by MastaFoo** [comment]
Vive Pro 2, Wireless adapter. this made things worse. like unplayably so. 

[OpenVR] Initialising OpenVR
[OpenVR] Stretched Width/Height from 1664x1664 to 2202x2202
[OpenVR] Desired fov = 96.7607 Desired aspect ratio = 1.44504

**Comment by codyherzog** [comment]
Attaching d3d9.dll which adds a bunch more logging and removes my previous scaling hack. This might be useful to run on problematic configurations in order to gather more data.
[d3d9 - logging.zip](https://github.com/user-attachments/files/18000097/d3d9.-.logging.zip)

**Comment by LivingFray** [comment]
I'm wondering if this issue is related to how halo calculates the viewport size (which I currently override to [-1.0,1.0] on each axis in H_SetViewportScale)

This is the (poorly) decompiled code for the original game function, in case anyone can divine what exactly it is trying to do + what the mod should be doing to account for it.
``` void __fastcall Renderer::SetViewportSize(int numViews,sRect *vp,int currentView,sRect *othervp)

{
  ushort doSplitscreen;
  int yIndex;
  int innerHeight;
  int borderHeight;
  int numX;
  int xIndex;
  int numY2;
  short sYIndex;
  short viewHeight;
  short left;
  short right;
  short borderWidth;
  byte bStretchP1;
  byte bStretchP1Also;
  undefined4 borderHeight2;
  short sXIndex;
  short viewWidth;
  
  numX = 1;
  bStretchP1 = 0;
  bStretchP1Also = 0;
  doSplitscreen = (numViews < 2) - 1 & 4;
  borderHeight = 1;
  numY2 = 1;
  if (1 < numViews) {
    do {
      if (numX < borderHeight) {
        numX += 1;
      }
      else {
        numX = 1;
        borderHeight += 1;
      }
      numY2 = borderHeight;
    } while (borderHeight * numX < numViews);
  }
  if (numY2 * numX - numViews != 0 && numViews <= numY2 * numX) {
    if (currentView == 0) {
      bStretchP1 = 1;
      bStretchP1Also = 1;
    }
    else {
      currentView += 1;
    }
  }
  yIndex = currentView / numX;
  borderHeight = (int)gWindowHeightBorder;
  xIndex = currentView - numX * yIndex;
  innerHeight = (int)gWindowInnerHeight;
  borderWidth = gWindowWidthBorder;
  viewWidth = (short)(((int)gWindowInnerWidth - (int)gWindowWidthBorder) / numX) * (bStretchP1 + 1);
  sXIndex = (short)xIndex;
  vp->left = viewWidth * sXIndex + gWindowWidthBorder;
  borderHeight2 = _gWindowHeightBorder;
  vp->right = (sXIndex + 1) * viewWidth + borderWidth;
  sYIndex = (short)yIndex;
  viewHeight = (short)((innerHeight - borderHeight) / numY2);
  vp->top = sYIndex * viewHeight + (short)borderHeight2;
  left = vp->left;
  vp->bottom = (sYIndex + 1) * viewHeight + (short)borderHeight2;
  othervp->top = vp->top;
  othervp->left = left;
  right = vp->right;
  othervp->bottom = vp->bottom;
  othervp->right = right;
  vp->left = vp->left + sXIndex * doSplitscreen;
  vp->right = vp->right - (xIndex == 0) * doSplitscreen;
  vp->top = vp->top + sYIndex * doSplitscreen;
  vp->bottom = vp->bottom - (yIndex == 0) * doSplitscreen;
  if (xIndex == 0) {
    othervp->left = gWindowRect.left;
  }
  if (bStretchP1Also + 1 + xIndex == numX) {
    othervp->right = gWindowRect.right;
  }
  if (yIndex == 0) {
    othervp->top = gWindowRect.top;
  }
  if (yIndex + 1 == numY2) {
    othervp->bottom = gWindowRect.bottom;
  }
  return;
}

```

**Comment by cubiclestorm** [comment]
the dll worked for me using a Quest 3 through Virtual Desktop

**Comment by codyherzog** [comment]
Perhaps as a temporary measure there could be config parameters for tweaking the width/height scale factor. People could then experiment and find values that work in their configurations, which combined with the verbose logging might help us understand how to make a real fix.

**Comment by codyherzog** [comment]
Now that the viewport scaling parameters have been exposed, I've reduced the scope of this PR to simply add some detailed logging for GetProjectionRaw() and related code. I'm not sure we want or need this, so let me know and I'll close it if desired. I suppose it might still be helpful to debug the head tilt warping issue. Thanks.

**Comment by LivingFray** [comment]
Forgot about this PR, might as well merge it in case it makes things easier for people setting their own viewport scaling/debugging the root cause

**Pull request merged**
